"""자연어 추천 프롬프트 모듈.

LLM 기반 자연어 추천 시스템에서 사용하는 프롬프트를 정의합니다.
"""

from .context_extraction import (
    CONTEXT_EXTRACTION_SYSTEM_PROMPT,
    CONTEXT_EXTRACTION_USER_PROMPT_TEMPLATE,
)
from .query_generation import (
    QUERY_GENERATION_SYSTEM_PROMPT,
    QUERY_GENERATION_USER_PROMPT_TEMPLATE,
)
from .recommendation_reason import (
    RECOMMENDATION_REASON_SYSTEM_PROMPT,
    RECOMMENDATION_REASON_USER_PROMPT_TEMPLATE,
)

__all__ = [
    "CONTEXT_EXTRACTION_SYSTEM_PROMPT",
    "CONTEXT_EXTRACTION_USER_PROMPT_TEMPLATE",
    "QUERY_GENERATION_SYSTEM_PROMPT",
    "QUERY_GENERATION_USER_PROMPT_TEMPLATE",
    "RECOMMENDATION_REASON_SYSTEM_PROMPT",
    "RECOMMENDATION_REASON_USER_PROMPT_TEMPLATE",
]
