// This file will be auto-generated by Supabase CLI
// Run: supabase gen types typescript --local > src/types/database.types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      certificates: {
        Row: {
          id: string
          code: string
          category_name: string
          series: string
          title: string
          status: 'raw' | 'enriched'
          overview: string | null
          key_points: string[] | null
          difficulty: number | null
          pass_rate: number | null
          study_period_days: number | null
          study_tips: string[] | null
          job_prospects: string | null
          recommended_lectures: Json | null
          exam_info: Json | null
          resources: Json | null
          enriched_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          code: string
          category_name: string
          series: string
          title: string
          status?: 'raw' | 'enriched'
          overview?: string | null
          key_points?: string[] | null
          difficulty?: number | null
          pass_rate?: number | null
          study_period_days?: number | null
          study_tips?: string[] | null
          job_prospects?: string | null
          recommended_lectures?: Json | null
          exam_info?: Json | null
          resources?: Json | null
          enriched_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          code?: string
          category_name?: string
          series?: string
          title?: string
          status?: 'raw' | 'enriched'
          overview?: string | null
          key_points?: string[] | null
          difficulty?: number | null
          pass_rate?: number | null
          study_period_days?: number | null
          study_tips?: string[] | null
          job_prospects?: string | null
          recommended_lectures?: Json | null
          exam_info?: Json | null
          resources?: Json | null
          enriched_at?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      study_plans: {
        Row: {
          id: string
          user_id: string
          certificate_id: string
          target_date: string
          daily_hours: number
          weekly_schedule: Json | null
          milestones: Json | null
          status: 'active' | 'completed' | 'paused' | 'cancelled'
          progress: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          certificate_id: string
          target_date: string
          daily_hours: number
          weekly_schedule?: Json | null
          milestones?: Json | null
          status?: 'active' | 'completed' | 'paused' | 'cancelled'
          progress?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          certificate_id?: string
          target_date?: string
          daily_hours?: number
          weekly_schedule?: Json | null
          milestones?: Json | null
          status?: 'active' | 'completed' | 'paused' | 'cancelled'
          progress?: number
          created_at?: string
          updated_at?: string
        }
      }
      checkins: {
        Row: {
          id: string
          user_id: string
          study_plan_id: string
          date: string
          duration_minutes: number
          notes: string | null
          completed_tasks: string[] | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          study_plan_id: string
          date: string
          duration_minutes: number
          notes?: string | null
          completed_tasks?: string[] | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          study_plan_id?: string
          date?: string
          duration_minutes?: number
          notes?: string | null
          completed_tasks?: string[] | null
          created_at?: string
        }
      }
      profiles: {
        Row: {
          id: string
          email: string
          full_name: string | null
          avatar_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          full_name?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          full_name?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

// Helper types
export type Certificate = Database['public']['Tables']['certificates']['Row']
export type CertificateInsert = Database['public']['Tables']['certificates']['Insert']
export type CertificateUpdate = Database['public']['Tables']['certificates']['Update']

export type StudyPlan = Database['public']['Tables']['study_plans']['Row']
export type StudyPlanInsert = Database['public']['Tables']['study_plans']['Insert']
export type StudyPlanUpdate = Database['public']['Tables']['study_plans']['Update']

export type Checkin = Database['public']['Tables']['checkins']['Row']
export type CheckinInsert = Database['public']['Tables']['checkins']['Insert']
export type CheckinUpdate = Database['public']['Tables']['checkins']['Update']

export type Profile = Database['public']['Tables']['profiles']['Row']
export type ProfileInsert = Database['public']['Tables']['profiles']['Insert']
export type ProfileUpdate = Database['public']['Tables']['profiles']['Update']

